# fly.toml app configuration file generated for ntnu-database-2023-final on 2023-06-14T16:58:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ntnu-database-2023-final"
primary_region = "hkg"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  APP_URL = "db-ntnu.jw910731.me"
  APP_NAME = "NTNU DB 2023"
  DB_CONNECTION = "mysql"
  DB_HOST = "140.122.184.125"
  DB_PORT = "3307"
  DB_DATABASE = "team6"
  DB_USERNAME = "team6"
#  DB_CONNECTION = "pgsql"
#  DB_HOST = "silent-tree-5494.internal"
#  DB_PORT = "5432"
#  DB_DATABASE = "postgres"
#  DB_USERNAME = "postgres"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
